import Link from "next/link";

export const metadata = { title: "Terms of Service — Acquisition Exchange" };

export default function TermsPage() {
  return (
    <div style={{ maxWidth: 720, margin: "0 auto", padding: "64px 24px 80px", fontFamily: "'Inter','Segoe UI',system-ui,sans-serif" }}>
      <Link href="/" style={{ display: "inline-flex", alignItems: "center", gap: 8, textDecoration: "none", marginBottom: 40 }}>
        <div style={{ width: 32, height: 32, borderRadius: 8, background: "linear-gradient(135deg,#166534,#14532d)", display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontWeight: 700, fontSize: 15 }}>T</div>
        <span style={{ fontWeight: 700, fontSize: 16, color: "#1c1917", letterSpacing: "-0.02em" }}>Acquisition Exchange</span>
      </Link>

      <h1 style={{ fontSize: 28, fontWeight: 800, color: "#1c1917", margin: "0 0 8px", letterSpacing: "-0.03em" }}>Terms of Service</h1>
      <p style={{ fontSize: 13, color: "#78716c", margin: "0 0 40px" }}>Last updated: 30 June 2026</p>

      <div style={{ fontSize: 14, color: "#44403c", lineHeight: 1.75, display: "flex", flexDirection: "column", gap: 24 }}>
        <section>
          <h2 style={{ fontSize: 16, fontWeight: 700, color: "#1c1917", margin: "0 0 8px" }}>1. Acceptance of Terms</h2>
          <p>By accessing or using Acquisition Exchange (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
        </section>

        <section>
          <h2 style={{ fontSize: 16, fontWeight: 700, color: "#1c1917", margin: "0 0 8px" }}>2. Description of Service</h2>
          <p>Acquisition Exchange provides deal analysis and credit assessment tools for UK SME acquisitions. The Service is intended for informational purposes only and does not constitute financial advice.</p>
        </section>

        <section>
          <h2 style={{ fontSize: 16, fontWeight: 700, color: "#1c1917", margin: "0 0 8px" }}>3. Not Financial Advice</h2>
          <p>All content, analysis, scores, and outputs generated by the Service are for informational purposes only. Acquisition Exchange is not a regulated financial adviser. Nothing on this platform constitutes investment, legal, or financial advice. Always consult a qualified professional before making acquisition decisions.</p>
        </section>

        <section>
          <h2 style={{ fontSize: 16, fontWeight: 700, color: "#1c1917", margin: "0 0 8px" }}>4. User Accounts</h2>
          <p>You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must notify us immediately of any unauthorised use.</p>
        </section>

        <section>
          <h2 style={{ fontSize: 16, fontWeight: 700, color: "#1c1917", margin: "0 0 8px" }}>5. Subscriptions and Billing</h2>
          <p>Paid subscriptions are billed monthly. You may cancel at any time through the billing portal. Refunds are not provided for partial billing periods except where required by law.</p>
        </section>

        <section>
          <h2 style={{ fontSize: 16, fontWeight: 700, color: "#1c1917", margin: "0 0 8px" }}>6. Acceptable Use</h2>
          <p>You agree not to misuse the Service, attempt to gain unauthorised access, scrape data in bulk, or use the Service for any unlawful purpose.</p>
        </section>

        <section>
          <h2 style={{ fontSize: 16, fontWeight: 700, color: "#1c1917", margin: "0 0 8px" }}>7. Limitation of Liability</h2>
          <p>To the fullest extent permitted by law, Acquisition Exchange shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.</p>
        </section>

        <section>
          <h2 style={{ fontSize: 16, fontWeight: 700, color: "#1c1917", margin: "0 0 8px" }}>8. Contact</h2>
          <p>For questions about these terms, contact us at <a href="mailto:hello@acquisition.exchange" style={{ color: "#1c1917" }}>hello@acquisition.exchange</a>.</p>
        </section>
      </div>
    </div>
  );
}
